using UnityEngine;
using UnityEngine.UI;
using ArenaDeathMatch.Utilities;

namespace ArenaDeathMatch.UI.Screens
{
    // The StatisticsScreen displays the statistical tables generated by StatisticalTablesGenerator.
    // It inherits from UIScreen so that it can be managed by UIManager.
    public class StatisticsScreen : UIScreen
    {
        [Header("UI Elements")]
        [SerializeField] private Text statisticsText;  // Assign via Inspector to the Text component that displays the stats

        protected override void Awake()
        {
            base.Awake();
            if (statisticsText == null)
            {
                Debug.LogError("StatisticsScreen: statisticsText is not assigned. Please assign a UI Text component in the inspector.");
            }
        }

        // When the statistics screen is shown, refresh the contents to display the latest report.
        public override void Show(UITransitionData transitionData = null)
        {
            base.Show(transitionData);
            RefreshStatistics();
        }

        // Refreshes the statistics text with the latest generated report.
        public void RefreshStatistics()
        {
            if (statisticsText != null)
            {
                statisticsText.text = StatisticalTablesGenerator.GenerateStatisticsReport();
            }
        }

        // Callback for a back button in the UI.
        // This method can be hooked up to a UI button to allow the user to return to the previous screen.
        public void OnBackButtonClicked()
        {
            UIManager.Instance.GoBack();
        }
    }
}
